a = {
    '103.227.128.16':
        {
            '47.91.163.77':[
                'login.efun.com',
                'ptlogin.efun.com',
                'loginsea.efunsea.com',
                'ptlogin.efunsea.com',
                'https://sdksea-file-download.efunsea.com/policy/all/en_US/efun.html'
            ],
            '47.91.163.76':[
                'award.efun.com',
                'awardip.efun.com',
                'exchange.efun.com',
                'exchangeip.efun.com',
                'pay.efun.com',
                'payip.efun.com',
                'ptpay.efun.com',
                'paysea.efunsea.com'
            ],
            '47.90.109.102':[
                'login.aseugame.com',
                'loginsea.aseugame.com',
                'ptlogin.aseugame.com',
                'ptloginsea.aseugame.com',
                'https://sdksea-file-download.aseugame.com/policy/all/en_US/efun.html'
            ],
            '47.90.109.103':[
                'award.aseugame.com',
                'pay.aseugame.com',
                'paysea.aseugame.com'
            ],
            '47.90.109.104':[
                'activity.aseugame.com',
                'e.aseugame.com',
                'fb.aseugame.com',
                'fbsea.aseugame.com',
                'game.aseugame.com',
                'gamesea.aseugame.com',
                'pf.aseugame.com',
                'pfid.aseugame.com',
                'pfnvn.aseugame.com'
            ],
            '47.90.120.12':[
                'pf-assist.efunen.com',
                'push.efun.com'
            ],
            '47.91.159.181':[
                'activity-assist.efun.com'
            ],
            '103.227.130.141':[
                'ad-h5.eflygame.com',
                'h5.eflygame.com',
                'www.eflygame.com',
                'login-h5.eflygame.com',
                'pay-h5.eflygame.com',
                'user-h5.eflygame.com',
                'pf-h5.eflygame.com',
                'lua-h5.eflygame.com'
            ]
        },
    '50.18.119.120':
        {
            '52.53.74.206':[
                'activity.app4gamer.com',
                'activity-assist.app4gamer.com',
                'activity-assist.efunsa.com',
                'activity.efunsa.com',
                'ad.efunsa.com',
                'adus.app4gamer.com',
                'assist.efunsa.com',
                'exchange.efunsa.com',
                'fb.app4gamer.com',
                'fb.efunsa.com',
                'game.app4gamer.com',
                'game.efunsa.com',
                'login.app4gamer.com',
                'login.efunsa.com',
                'm.app4gamer.com',
                'm.efunsa.com',
                'pay.app4gamer.com',
                'pay.efunsa.com',
                'pf.app4gamer.com',
                'pf-assist.app4gamer.com',
                'pf-assist.efunsa.com',
                'pf.efunsa.com',
                'https://sdksa-file-download.app4gamer.com/policy/all/en_US/efun.html',
                'https://sdksa-file-download.efunsa.com/policy/all/en_US/efun.html',
                'toosl.efunsa.com',
                'www.app4gamer.com',
                'www.efunsa.com'
            ],
            '52.52.168.218':[
                'adsa.app4gamer.com',
                'adsa.aseugame.com',
                'assistsa.app4gamer.com',
                'assistsa.aseugame.com',
                'exchangesa.app4gamer.com',
                'exchangesa.aseugame.com',
                'fbsa.app4gamer.com',
                'fbsa.aseugame.com',
                'gamesa.app4gamer.com',
                'gamesa.aseugame.com',
                'loginsa.app4gamer.com',
                'loginsa.aseugame.com',
                'paysa.app4gamer.com',
                'paysa.aseugame.com',
                'https://sdksa-file-download.aseugame.com/policy/all/en_US/efun.html',
                'toolssa.app4gamer.com',
                'toolssa.aseugame.com'
            ]
        },
    '203.69.109.117':{
        '52.197.36.117':[
            'ad.efunjp.com',
            'ad.reginaet.jp',
            'assist.efunjp.com',
            'assist.reginaet.jp',
            'exchange.efunjp.com',
            'exchange.reginaet.jp',
            'fb.efunjp.com',
            'fb.reginaet.jp',
            'game.efunjp.com',
            'game.reginaet.jp',
            'login.efunjp.com',
            'login.reginaet.jp',
            'pay.efunjp.com',
            'pay.reginaet.jp',
            'sdk-file-download.efunjp.com',
            'sdk-file-download.reginaet.jp',
            'tools.efunjp.com'
        ]
    },
    '58.229.180.29':{
        '52.79.191.172':[
            'activity-assist.yh666kr.com',
            'activity.yh666kr.com',
            'ad.yh666kr.com',
            'assist.yh666kr.com',
            'esou.yh666kr.com',
            'exchange.yh666kr.com',
            'fb.yh666kr.com',
            'game.yh666kr.com',
            'login.yh666kr.com',
            'pay.yh666kr.com',
            'pf.yh666kr.com',
            'tools.yh666kr.com',
            'www.yh666kr.com'
        ],
        '58.229.184.41':[
            'activity.chaseol.com',
            'ad.chaseol.com',
            'assist.chaseol.com',
            'exchange.chaseol.com',
            'fb.chaseol.com',
            'game.chaseol.com',
            'log.chaseol.com',
            'login.chaseol.com',
            'pay.chaseol.com',
            'pf-assist.chaseol.com',
            'pf.chaseol.com',
            'sdk-file-download.chaseol.com',
            'www.chaseol.com',
            'activity-assist.chaseol.com'
        ]
    }
}


